### ISSUE TITLE
IdP Initiated SSO (single-sign-on)

### ISSUE THREAD

**Issue by njd5475** [lawrencepit/ruby-saml-idp#18]
Hopefully this is a pretty quick and easy answer. But how do you generate a SAML response without a request for a specific service provider?

I know I can use encode_response, is it just a matter of overriding the methods in the SAMLIdp::Controller? 

Any help or pointing in the right direction is appreciated.

**Comment by njd5475** [comment]
@pbssubhash No I had no luck, I'm not that knowledgable about SAML.

**Comment by lawrencepit** [comment]
Yes, it's just a matter of overriding the methods in `SamlIdp::IdpController`, like for example so:

```
class SamlIdpController < SamlIdp::IdpController

  def idp_authenticate(email, password)
    { :email => email }
  end

  def idp_make_saml_response(user)
    encode_SAMLResponse(user[:email])
  end

end
```

Otherwise, see [this spec](https://github.com/lawrencepit/ruby-saml-idp/blob/c16baa42df45d7a69556c15f9939e38edcc5bac2/spec/saml_idp/controller_spec.rb#L24)
