### ISSUE TITLE
SECURITY: Update ruby-saml gem dependency to 1.7 to patch new SAML vulnerability

### ISSUE THREAD

**Issue by ranierorusso** [lawrencepit/ruby-saml-idp#28]
OneLogin just alerted its users to a new SAML vulnerability. They have already patched their ruby-saml gem in version 1.7 and this gem should now be referencing that version (https://github.com/lawrencepit/ruby-saml-idp/blob/728fd8b579c567404b6f76ca8583445000f5b234/ruby-saml-idp.gemspec#L30). 

Here's the patch in onelogin/ruby-saml: https://github.com/onelogin/ruby-saml/commit/048a544730930f86e46804387a6b6fad50d8176f

I can open a PR for this change if you'd like but hopefully this can get patched as soon as possible!

Thank you.

**Comment by lawrencepit** [comment]
This gem does not have a dependency on the ruby-saml gem, only a development dependency to run the tests.

**Comment by lawrencepit** [comment]
Pushed v0.3.5
