### ISSUE TITLE
present? couples to activesupport

### ISSUE THREAD

**Issue by kevinburkeomg** [lawrencepit/ruby-saml-idp#31]
The calls to `present?` in the controller mean that we're coupled to ActiveSupport, since that's the library that puts that function on the String class. It would be good to either add an explicit `require`, update the docs or change the function to use default methods on the `String` object.

**Comment by lawrencepit** [comment]
See commit [c16baa42](https://github.com/lawrencepit/ruby-saml-idp/commit/c16baa42df45d7a69556c15f9939e38edcc5bac2)
